export const seedActivityLogs = [
  {
    parentId: null, // parentId to be filled after user insert
    childId: null, // childId to be filled after user insert
    childName: "Emily Doe",
    type: "LOGIN",
    message: "Emily logged in",
    value: 1,
    timestamp: new Date(),
  },
  {
    parentId: null,
    childId: null,
    childName: "Emily Doe",
    type: "CHILD_ADDED_SKILL",
    message: "Emily added Math skill",
    value: 5,
    timestamp: new Date(Date.now() - 86400000 * 1),
  },
  {
    parentId: null,
    childId: null,
    childName: "Emily Doe",
    type: "WATCHED_VIDEO",
    message: "Emily watched STEM learning video",
    value: 10,
    timestamp: new Date(Date.now() - 86400000 * 2),
  },
  {
    parentId: null,
    childId: null,
    childName: "Ryan Doe",
    type: "LOGIN",
    message: "Ryan logged in",
    value: 1,
    timestamp: new Date(),
  },
  {
    parentId: null,
    childId: null,
    childName: "Ryan Doe",
    type: "LIKED",
    message: "Ryan liked a post",
    value: 3,
    timestamp: new Date(Date.now() - 86400000 * 3),
  },
  {
    parentId: null,
    childId: null,
    childName: "Ryan Doe",
    type: "JOINED_CHANNEL",
    message: "Ryan joined Robotics group",
    value: 4,
    timestamp: new Date(Date.now() - 86400000 * 5),
  },
  {
    parentId: null,
    childId: null,
    childName: "Arjun Kapoor",
    type: "LOGIN",
    message: "Arjun logged in",
    value: 1,
    timestamp: new Date(),
  },
  {
    parentId: null,
    childId: null,
    childName: "Arjun Kapoor",
    type: "CHILD_ADDED_PROJECT",
    message: "Arjun added Solar System project",
    value: 12,
    timestamp: new Date(Date.now() - 86400000 * 2),
  },
  {
    parentId: null,
    childId: null,
    childName: "Arjun Kapoor",
    type: "CHILD_ADDED_ACHIEVEMENT",
    message: "Arjun won story contest",
    value: 8,
    timestamp: new Date(Date.now() - 86400000 * 4),
  },
  {
    parentId: null,
    childId: null,
    childName: "Riya Kapoor",
    type: "LOGIN",
    message: "Riya logged in",
    value: 1,
    timestamp: new Date(),
  },
  {
    parentId: null,
    childId: null,
    childName: "Riya Kapoor",
    type: "WATCHED_VIDEO",
    message: "Riya watched dance tutorial",
    value: 5,
    timestamp: new Date(Date.now() - 86400000 * 1),
  },
  {
    parentId: null,
    childId: null,
    childName: "Sara Shah",
    type: "LOGIN",
    message: "Sara logged in",
    value: 1,
    timestamp: new Date(),
  },
  {
    parentId: null,
    childId: null,
    childName: "Sara Shah",
    type: "ENROLLED_COURSE",
    message: "Sara enrolled into puzzle solving course",
    value: 7,
    timestamp: new Date(Date.now() - 86400000 * 2),
  },
  {
    parentId: null,
    childId: null,
    childName: "Daniel Shah",
    type: "LOGIN",
    message: "Daniel logged in",
    value: 1,
    timestamp: new Date(),
  },
  {
    parentId: null,
    childId: null,
    childName: "Daniel Shah",
    type: "CHILD_ADDED_INTEREST",
    message: "Daniel added Football interest",
    value: 6,
    timestamp: new Date(Date.now() - 86400000 * 2),
  },
  {
    parentId: null,
    childId: null,
    childName: "Zoya Singh",
    type: "LOGIN",
    message: "Zoya logged in",
    value: 1,
    timestamp: new Date(),
  },
  {
    parentId: null,
    childId: null,
    childName: "Zoya Singh",
    type: "CHILD_UPDATED_PROFILE",
    message: "Zoya updated drawing profile",
    value: 4,
    timestamp: new Date(Date.now() - 86400000 * 3),
  },
  {
    parentId: null,
    childId: null,
    childName: "Kabir Singh",
    type: "LOGIN",
    message: "Kabir logged in",
    value: 1,
    timestamp: new Date(),
  },
  {
    parentId: null,
    childId: null,
    childName: "Kabir Singh",
    type: "WATCHED_VIDEO",
    message: "Kabir watched cricket training lesson",
    value: 9,
    timestamp: new Date(Date.now() - 86400000 * 3),
  },
  {
    parentId: null,
    childId: null,
    childName: "Ananya Mehra",
    type: "LOGIN",
    message: "Ananya logged in",
    value: 1,
    timestamp: new Date(),
  },
  {
    parentId: null,
    childId: null,
    childName: "Ananya Mehra",
    type: "LIKED",
    message: "Ananya liked a science post",
    value: 3,
    timestamp: new Date(Date.now() - 86400000 * 2),
  },
  {
    parentId: null,
    childId: null,
    childName: "Aarav Mehra",
    type: "LOGIN",
    message: "Aarav logged in",
    value: 1,
    timestamp: new Date(),
  },
  {
    parentId: null,
    childId: null,
    childName: "Aarav Mehra",
    type: "CHILD_ADDED_INTEREST",
    message: "Aarav added Animals interest",
    value: 5,
    timestamp: new Date(Date.now() - 86400000 * 3),
  },
];
